### ISSUE TITLE
Merge winnewoerp-patch-1 branch

### ISSUE THREAD

**Issue by winnewoerp** [Luensche/my-transit-lines#16]
Merge winnewoerp-ptach-1 branch to master. Important because one fatal error in functions.php has been removed.

(Or tell "Mr. Github newbie" how to do it. :) )

**Comment by Luensche** [comment]
You can easy create a [pull request](https://github.com/Luensche/my-transit-lines/compare). If it's a normal enhancement for the next release request a pull to development, otherwise directly to master.

**Comment by winnewoerp** [comment]
Thank you, done!
